### PR TITLE
Jason Test Branch

### PR DESCRIPTION
**Pull request by jwtufano**
Main is just about finished, probably has some unnecessary stuff but
whatever.

Added colMatrix and rowMatrix because the first column was needed for
part of the assignment.

Also edited your comments because I didn’t like them.

P.S. AM I PULL REQUESTING CORRECTLY?

### CODE REVIEW

**Comment by andy29485** [comment]
Why are you requesting a pull?
You can do it your self, cant you... this feature is intended for people that are not part of the project but want to contribute. (doesn't really apply to our case right now)

**Comment by andy29485** [comment]
I think that you just want to **push** not **pull request**.

**Comment by jwtufano** [comment]
I don't know what I'm doing that's why

**Comment by andy29485** [comment]
Ok, here's what you do:
1. checkout **master**
2. merge **Jason-Test_Branch** into **master**
3. push(or sync, I think)

**Comment by jwtufano** [comment]
8
2
5
seems legit

And I think I did it? idk

**Comment by andy29485** [comment]
I was testing [this](http://puu.sh/lD5Sv/6cb4cb33b4.png)

**Comment by jwtufano** [comment]
5
4
3
1
Off Blast

**Comment by andy29485** [comment]
http://imgur.com/gallery/i2Z5A

**Pull request merged**
